services:
  - type: web
    name: fleet-erp-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
